### ISSUE TITLE
在02-FlyFish 平台部署篇 初始化数据库时发现一个文档中疏漏或者说是bug

### ISSUE THREAD

**Issue by jimmy201602** [CloudWise-OpenSource/FlyFish#119]
### 描述 Bug

根据文档中安装部署步骤，在02-FlyFish 平台部署篇 初始化数据库时发现一个文档中疏漏或者说是bug

### 复现 Bug
```sh
[root@docker lcapServer]# npm run init-development-database

> FlyFish@1.0.0 init-development-database /data/app/FlyFish/lcapServer
> EGG_SERVER_ENV=development cd changelog && node scripts/initDatabase.js

MongoServerSelectionError: getaddrinfo ENOTFOUND flyfish-mongo
    at Timeout._onTimeout (/data/app/FlyFish/lcapServer/node_modules/mongodb/lib/sdam/topology.js:305:38)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
后经过排查发现是mongodb串错误，经搜索错误的mongo连接字符串，mongodb://flyfish-mongo:27017/flyfish ，发现此字符串出现在config/config.docker.js
<img width="643" alt="image" src="https://user-images.githubusercontent.com/17548183/169228046-dc8d8170-319a-4950-b558-20d0f3729738.png">
经修改连接字符串，后初始化数据库正常
按道理docker部分的配置文件不应该出现在本地部署的文档中，应是文档中疏漏或者是引用变量时混了

**Comment by jincheny** [comment]
开源版本FlyFish-2.1.1暂未提供完整版docker部署方案，doc中部署文档目前只针对Centos7.6环境下传统线上环境部署方案。
config.docker.js 属于企业版本历史残留文件。开源版本会考虑提供并补充完整的docker部署方案。
